/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.automercado.ui;

import com.automercado.bo.EmpleadoBO;
import com.automercado.entity.Empleado;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author kev17
 */
public class FrmEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form FrmEmpleado
     */
    private EmpleadoBO ebo = new EmpleadoBO();

    public FrmEmpleado() {
        initComponents();
        setLocationRelativeTo(null);
        cargarTablaEmpleados();
    }

    public void listarEmpleado() {
        ebo.listaEmpleado(tblEmpleados);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblIdEmpleado = new javax.swing.JLabel();
        lblNombreEmpleado = new javax.swing.JLabel();
        lblCargoEmpleado = new javax.swing.JLabel();
        lblFechaContratacionEmpleado = new javax.swing.JLabel();
        lblSalarioEmpleado = new javax.swing.JLabel();
        lblGerenteEmpleado = new javax.swing.JLabel();
        txtIdEmpleado = new javax.swing.JTextField();
        txtNombreEmpleado = new javax.swing.JTextField();
        txtCargoEmpleado = new javax.swing.JTextField();
        dtFechaContratacionEmpleado = new com.toedter.calendar.JDateChooser();
        txtSalarioEmpleado = new javax.swing.JTextField();
        txtGerenteEmpleado = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        btnAgregarEmpleado = new javax.swing.JButton();
        btnModificarEmpleado = new javax.swing.JButton();
        btnEliminarEmpleado = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        lblImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblTitulo.setText("EMPLEADOS");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        lblIdEmpleado.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblIdEmpleado.setText("ID:");
        jPanel1.add(lblIdEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        lblNombreEmpleado.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblNombreEmpleado.setText("NOMBRE:");
        jPanel1.add(lblNombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 30));

        lblCargoEmpleado.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblCargoEmpleado.setText("CARGO:");
        jPanel1.add(lblCargoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 70, 30));

        lblFechaContratacionEmpleado.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblFechaContratacionEmpleado.setText("FECHA CONTRATACION:");
        jPanel1.add(lblFechaContratacionEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 30));

        lblSalarioEmpleado.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblSalarioEmpleado.setText("SALARIO:");
        jPanel1.add(lblSalarioEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, 30));

        lblGerenteEmpleado.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblGerenteEmpleado.setText("GERENTE:");
        jPanel1.add(lblGerenteEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 90, 30));

        txtIdEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 100, 30));

        txtNombreEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 220, 30));

        txtCargoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargoEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCargoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 220, 30));
        jPanel1.add(dtFechaContratacionEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 130, 30));

        txtSalarioEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(txtSalarioEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 200, 30));

        txtGerenteEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGerenteEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(txtGerenteEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 200, 30));

        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblEmpleados);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 87, 520, 390));

        btnAgregarEmpleado.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnAgregarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automercado/icon/mas_icon.png"))); // NOI18N
        btnAgregarEmpleado.setText("Agregar");
        btnAgregarEmpleado.setToolTipText("");
        btnAgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 120, 30));

        btnModificarEmpleado.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnModificarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automercado/icon/editar_icon.png"))); // NOI18N
        btnModificarEmpleado.setText("Modificar");
        btnModificarEmpleado.setToolTipText("");
        btnModificarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 120, 30));

        btnEliminarEmpleado.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnEliminarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automercado/icon/borrar_icon.png"))); // NOI18N
        btnEliminarEmpleado.setText("Eliminar");
        btnEliminarEmpleado.setToolTipText("");
        btnEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 120, 30));

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automercado/icon/limpiar_icon.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setToolTipText("");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 120, 30));

        btnVolver.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automercado/icon/atras_icon.png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setToolTipText("");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 50, 110, 30));

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automercado/img/empleados.jpg"))); // NOI18N
        jPanel1.add(lblImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGerenteEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGerenteEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGerenteEmpleadoActionPerformed

    private void txtIdEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEmpleadoActionPerformed

    private void txtNombreEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEmpleadoActionPerformed

    private void txtCargoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargoEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargoEmpleadoActionPerformed

    private void txtSalarioEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioEmpleadoActionPerformed

    private void btnAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEmpleadoActionPerformed
        if (txtNombreEmpleado.getText().isEmpty() || txtCargoEmpleado.getText().isEmpty() || txtSalarioEmpleado.getText().isEmpty()
                || dtFechaContratacionEmpleado.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Por favor completo todos los campos");
        } else {
            Empleado emp = new Empleado();
            emp.setNombre_Empleado(txtNombreEmpleado.getText());
            emp.setCargo(txtCargoEmpleado.getText());
            Date fechaContratacion = dtFechaContratacionEmpleado.getDate();
            emp.setFecha_Contratacion(fechaContratacion);
            emp.setSalario(Integer.parseInt(txtSalarioEmpleado.getText()));
            emp.setId_Gerente(Integer.valueOf(txtGerenteEmpleado.getText()));

            EmpleadoBO empleadoBO = new EmpleadoBO();
            String mensaje = empleadoBO.agregarEmpleado(emp);

            JOptionPane.showMessageDialog(null, mensaje);
            limpiar();
            listarEmpleado();
            cargarTablaEmpleados();
        }
    }//GEN-LAST:event_btnAgregarEmpleadoActionPerformed

    private void btnModificarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarEmpleadoActionPerformed
        if (txtNombreEmpleado.getText().isEmpty() || txtCargoEmpleado.getText().isEmpty() || txtSalarioEmpleado.getText().isEmpty()
                || dtFechaContratacionEmpleado.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Por favor completo todos los campos");
        } else {
            Empleado emp = new Empleado();
            emp.setId_Empleado(Integer.parseInt(txtIdEmpleado.getText()));
            emp.setNombre_Empleado(txtNombreEmpleado.getText());
            emp.setCargo(txtCargoEmpleado.getText());
            Date fechaContratacion = dtFechaContratacionEmpleado.getDate();
            emp.setFecha_Contratacion(fechaContratacion);
            emp.setSalario(Integer.parseInt(txtSalarioEmpleado.getText()));
            emp.setId_Gerente(Integer.valueOf(txtGerenteEmpleado.getText()));

            EmpleadoBO empleadoBO = new EmpleadoBO();
            String mensaje = empleadoBO.modificarEmpleado(emp);

            JOptionPane.showMessageDialog(null, mensaje);
            limpiar();
            listarEmpleado();
            cargarTablaEmpleados();
        }
    }//GEN-LAST:event_btnModificarEmpleadoActionPerformed

    private void btnEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEmpleadoActionPerformed
        if (txtNombreEmpleado.getText().isEmpty() || txtCargoEmpleado.getText().isEmpty() || txtSalarioEmpleado.getText().isEmpty()
                || dtFechaContratacionEmpleado.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Por favor completo todos los campos");
        } else {
            EmpleadoBO empleadoBO = new EmpleadoBO();
            String mensaje = empleadoBO.eliminarEmpleado(Integer.parseInt(txtIdEmpleado.getText()));

            JOptionPane.showMessageDialog(null, mensaje);
            limpiar();
            listarEmpleado();
            cargarTablaEmpleados();
        }
    }//GEN-LAST:event_btnEliminarEmpleadoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        FrmIndex frmind = new FrmIndex();
        frmind.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void tblEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpleadosMouseClicked
        int seleccion = tblEmpleados.rowAtPoint(evt.getPoint());
        txtIdEmpleado.setText(tblEmpleados.getValueAt(seleccion, 0) + "");
        txtNombreEmpleado.setText(tblEmpleados.getValueAt(seleccion, 1) + "");
        txtCargoEmpleado.setText(tblEmpleados.getValueAt(seleccion, 2) + "");
        String fechaString = (String) tblEmpleados.getValueAt(seleccion, 3); // Cambia el índice si es necesario
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd"); // Ajusta el formato según sea necesario
        txtSalarioEmpleado.setText(tblEmpleados.getValueAt(seleccion, 4) + "");
        txtGerenteEmpleado.setText(tblEmpleados.getValueAt(seleccion, 5) + "");
        try {
            Date fechaRegistro = formato.parse(fechaString); //Convierte la cadena a Date
            dtFechaContratacionEmpleado.setDate(fechaRegistro); //Establece la fecha en el JDateChooser
        } catch (ParseException e) {
            e.printStackTrace(); //Maneja la excepción según sea necesario
            JOptionPane.showMessageDialog(null, "Error al convertir la fecha: " + e.getMessage());
        }
    }//GEN-LAST:event_tblEmpleadosMouseClicked

    public void limpiar() {
        txtIdEmpleado.setText("");
        txtNombreEmpleado.setText("");
        txtCargoEmpleado.setText("");
        dtFechaContratacionEmpleado.setDate(null);
        txtSalarioEmpleado.setText("");
        txtGerenteEmpleado.setText("");
    }

    private void cargarTablaEmpleados() {
        EmpleadoBO empleadoeBO = new EmpleadoBO();
        empleadoeBO.listaEmpleado(tblEmpleados);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEmpleado;
    private javax.swing.JButton btnEliminarEmpleado;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificarEmpleado;
    private javax.swing.JButton btnVolver;
    private com.toedter.calendar.JDateChooser dtFechaContratacionEmpleado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCargoEmpleado;
    private javax.swing.JLabel lblFechaContratacionEmpleado;
    private javax.swing.JLabel lblGerenteEmpleado;
    private javax.swing.JLabel lblIdEmpleado;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblNombreEmpleado;
    private javax.swing.JLabel lblSalarioEmpleado;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTextField txtCargoEmpleado;
    private javax.swing.JTextField txtGerenteEmpleado;
    private javax.swing.JTextField txtIdEmpleado;
    private javax.swing.JTextField txtNombreEmpleado;
    private javax.swing.JTextField txtSalarioEmpleado;
    // End of variables declaration//GEN-END:variables
}
