/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.automercado.ui;

/**
 *
 * @author kev17
 */
public class FrmIndex extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public FrmIndex() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panIndex = new javax.swing.JPanel();
        lblAutomercado = new javax.swing.JLabel();
        btnProductos = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnDetalleVentas = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnInventarios = new javax.swing.JButton();
        btnSucursales = new javax.swing.JButton();
        lblImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panIndex.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAutomercado.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblAutomercado.setText("AUTOMERCADO");
        panIndex.add(lblAutomercado, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 43, -1, -1));

        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automercado/icon/producto_icon.png"))); // NOI18N
        btnProductos.setText("PRODUCTOS");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        panIndex.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 201, 151, 55));

        btnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automercado/icon/proveedor_icon.png"))); // NOI18N
        btnProveedores.setText("PROVEEDORES");
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        panIndex.add(btnProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 274, 151, 55));

        btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automercado/icon/employees_icon.png"))); // NOI18N
        btnEmpleados.setText("EMPLEADOS");
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        panIndex.add(btnEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 347, 151, 55));

        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automercado/icon/ventas_icon.png"))); // NOI18N
        btnVentas.setText("VENTAS");
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        panIndex.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 128, 151, 55));

        btnDetalleVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automercado/icon/detalle_icon.png"))); // NOI18N
        btnDetalleVentas.setText("DETALLE VENTAS");
        btnDetalleVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalleVentasActionPerformed(evt);
            }
        });
        panIndex.add(btnDetalleVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 201, 151, 55));

        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automercado/icon/cliente_icon.png"))); // NOI18N
        btnClientes.setText("CLIENTES");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        panIndex.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 128, 151, 55));

        btnInventarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automercado/icon/inventario_icon.png"))); // NOI18N
        btnInventarios.setText("INVENTARIOS");
        btnInventarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventariosActionPerformed(evt);
            }
        });
        panIndex.add(btnInventarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 274, 151, 55));

        btnSucursales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automercado/icon/sucursal_icon.png"))); // NOI18N
        btnSucursales.setText("SUCURSALES");
        btnSucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSucursalesActionPerformed(evt);
            }
        });
        panIndex.add(btnSucursales, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 347, 151, 55));

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automercado/img/index.jpg"))); // NOI18N
        panIndex.add(lblImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 500));

        getContentPane().add(panIndex, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetalleVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalleVentasActionPerformed
        FrmDetalleVenta frmdven = new FrmDetalleVenta();
        frmdven.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDetalleVentasActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        FrmVenta frmven = new FrmVenta();
        frmven.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        FrmEmpleado frme = new FrmEmpleado();
        frme.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        FrmProveedor frmprov = new FrmProveedor();
        frmprov.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        FrmProducto frmprod = new FrmProducto();
        frmprod.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSucursalesActionPerformed
        FrmSucursal frmsuc = new FrmSucursal();
        frmsuc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSucursalesActionPerformed

    private void btnInventariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventariosActionPerformed
        FrmInventario frminv = new FrmInventario();
        frminv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnInventariosActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        FrmCliente frmc = new FrmCliente();
        frmc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmIndex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnDetalleVentas;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnInventarios;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnSucursales;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel lblAutomercado;
    private javax.swing.JLabel lblImg;
    private javax.swing.JPanel panIndex;
    // End of variables declaration//GEN-END:variables
}
