/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.automercado.ui;

import com.automercado.bo.ProductoBO;
import com.automercado.entity.Producto;
import javax.swing.JOptionPane;

/**
 *
 * @author kev17
 */
public class FrmProducto extends javax.swing.JFrame {

    /**
     * Creates new form FrmProducto
     */
    private ProductoBO pbo = new ProductoBO();
    
    public FrmProducto() {
        initComponents();
        setLocationRelativeTo(null);
        cargarTablaProductos();
    }
    
    public void listarProducto() {
        pbo.listaProducto(tblProductos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panProducto = new javax.swing.JPanel();
        lblIdProducto = new javax.swing.JLabel();
        lblNombreProducto = new javax.swing.JLabel();
        lblPrecioProducto = new javax.swing.JLabel();
        lblDescripcionProducto = new javax.swing.JLabel();
        lblStockProducto = new javax.swing.JLabel();
        lblCategoriaProducto = new javax.swing.JLabel();
        btnAgregarProducto = new javax.swing.JButton();
        btnModificarProducto = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        txtCategoriaProducto = new javax.swing.JTextField();
        txtStockProducto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDescripcionProducto = new javax.swing.JTextArea();
        txtIdProducto = new javax.swing.JTextField();
        txtPrecioProducto = new javax.swing.JTextField();
        txtNombreProducto = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIdProducto.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblIdProducto.setForeground(new java.awt.Color(51, 51, 51));
        lblIdProducto.setText("ID:");
        panProducto.add(lblIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        lblNombreProducto.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblNombreProducto.setForeground(new java.awt.Color(51, 51, 51));
        lblNombreProducto.setText("NOMBRE:");
        panProducto.add(lblNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 30));

        lblPrecioProducto.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblPrecioProducto.setForeground(new java.awt.Color(51, 51, 51));
        lblPrecioProducto.setText("PRECIO:");
        panProducto.add(lblPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 70, -1));

        lblDescripcionProducto.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblDescripcionProducto.setForeground(new java.awt.Color(51, 51, 51));
        lblDescripcionProducto.setText("DESCRIPCION:");
        panProducto.add(lblDescripcionProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 30));

        lblStockProducto.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblStockProducto.setForeground(new java.awt.Color(51, 51, 51));
        lblStockProducto.setText("STOCK:");
        panProducto.add(lblStockProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, 30));

        lblCategoriaProducto.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblCategoriaProducto.setForeground(new java.awt.Color(51, 51, 51));
        lblCategoriaProducto.setText("CATEGORIA:");
        panProducto.add(lblCategoriaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 110, 30));

        btnAgregarProducto.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnAgregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automercado/icon/mas_icon.png"))); // NOI18N
        btnAgregarProducto.setText("Agregar");
        btnAgregarProducto.setToolTipText("");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });
        panProducto.add(btnAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 120, 30));

        btnModificarProducto.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnModificarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automercado/icon/editar_icon.png"))); // NOI18N
        btnModificarProducto.setText("Modificar");
        btnModificarProducto.setToolTipText("");
        btnModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarProductoActionPerformed(evt);
            }
        });
        panProducto.add(btnModificarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 120, 30));

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automercado/icon/limpiar_icon.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setToolTipText("");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        panProducto.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 120, 30));

        btnEliminarProducto.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automercado/icon/borrar_icon.png"))); // NOI18N
        btnEliminarProducto.setText("Eliminar");
        btnEliminarProducto.setToolTipText("");
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });
        panProducto.add(btnEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 120, 30));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo.setText("PRODUCTOS");
        panProducto.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        txtCategoriaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoriaProductoActionPerformed(evt);
            }
        });
        panProducto.add(txtCategoriaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 200, 30));

        txtStockProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockProductoActionPerformed(evt);
            }
        });
        panProducto.add(txtStockProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 100, 30));

        txaDescripcionProducto.setColumns(10);
        txaDescripcionProducto.setLineWrap(true);
        txaDescripcionProducto.setRows(5);
        txaDescripcionProducto.setTabSize(1);
        txaDescripcionProducto.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txaDescripcionProducto);

        panProducto.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 340, 80));

        txtIdProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProductoActionPerformed(evt);
            }
        });
        panProducto.add(txtIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 100, 30));

        txtPrecioProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioProductoActionPerformed(evt);
            }
        });
        panProducto.add(txtPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 100, 30));

        txtNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProductoActionPerformed(evt);
            }
        });
        panProducto.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 220, 30));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProductos);

        panProducto.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 87, 480, 390));

        btnVolver.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automercado/icon/atras_icon.png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setToolTipText("");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        panProducto.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automercado/img/productos.jpg"))); // NOI18N
        panProducto.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        getContentPane().add(panProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        if (txtNombreProducto.getText().isEmpty() || txaDescripcionProducto.getText().isEmpty() || txtPrecioProducto.getText().isEmpty()
                || txtStockProducto.getText().isEmpty() || txtCategoriaProducto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor completo todos los campos");
        } else {
            Producto prod = new Producto();
            prod.setNombre_Producto(txtNombreProducto.getText());
            prod.setDescripcion(txaDescripcionProducto.getText());
            prod.setPrecio(Integer.parseInt(txtPrecioProducto.getText()));
            prod.setStock_Actual(Integer.parseInt(txtStockProducto.getText()));
            prod.setCategoria(txtCategoriaProducto.getText());
            
            ProductoBO productoBO = new ProductoBO();
            String mensaje = productoBO.agregarProducto(prod);
            JOptionPane.showMessageDialog(null, mensaje);
            
            limpiar();
            listarProducto();
            cargarTablaProductos();
        }
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProductoActionPerformed
        if (txtNombreProducto.getText().isEmpty() || txaDescripcionProducto.getText().isEmpty() || txtPrecioProducto.getText().isEmpty()
                || txtStockProducto.getText().isEmpty() || txtCategoriaProducto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor completo todos los campos");
        } else {
            Producto prod = new Producto();
            prod.setId_Producto(Integer.parseInt(txtIdProducto.getText()));
            prod.setNombre_Producto(txtNombreProducto.getText());
            prod.setDescripcion(txaDescripcionProducto.getText());
            prod.setPrecio(Integer.parseInt(txtPrecioProducto.getText()));
            prod.setStock_Actual(Integer.parseInt(txtStockProducto.getText()));
            prod.setCategoria(txtCategoriaProducto.getText());
            
            ProductoBO productoBO = new ProductoBO();
            String mensaje = productoBO.modificarProducto(prod);
            JOptionPane.showMessageDialog(null, mensaje);
            
            limpiar();
            listarProducto();
            cargarTablaProductos();
        }
    }//GEN-LAST:event_btnModificarProductoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        if (txtNombreProducto.getText().isEmpty() || txaDescripcionProducto.getText().isEmpty() || txtPrecioProducto.getText().isEmpty()
                || txtStockProducto.getText().isEmpty() || txtCategoriaProducto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor completo todos los campos");
        } else {
            ProductoBO productoBO = new ProductoBO();
            String mensaje = productoBO.eliminarProducto(Integer.parseInt(txtIdProducto.getText()));
            JOptionPane.showMessageDialog(null, mensaje);
            
            limpiar();
            listarProducto();
            cargarTablaProductos();
        }
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void txtCategoriaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoriaProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoriaProductoActionPerformed

    private void txtStockProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockProductoActionPerformed

    private void txtIdProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProductoActionPerformed

    private void txtPrecioProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioProductoActionPerformed

    private void txtNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        FrmIndex frmind = new FrmIndex();
        frmind.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        int seleccion = tblProductos.rowAtPoint(evt.getPoint());
        txtIdProducto.setText(tblProductos.getValueAt(seleccion, 0) + "");
        txtNombreProducto.setText(tblProductos.getValueAt(seleccion, 1) + "");
        txaDescripcionProducto.setText(tblProductos.getValueAt(seleccion, 2) + "");
        txtPrecioProducto.setText(tblProductos.getValueAt(seleccion, 3) + "");
        txtStockProducto.setText(tblProductos.getValueAt(seleccion, 4) + "");
        txtCategoriaProducto.setText(tblProductos.getValueAt(seleccion, 5) + "");
    }//GEN-LAST:event_tblProductosMouseClicked

    public void limpiar() {
        txtIdProducto.setText("");
        txtNombreProducto.setText("");
        txaDescripcionProducto.setText("");
        txtPrecioProducto.setText("");
        txtStockProducto.setText("");
        txtCategoriaProducto.setText("");
    }
    
    private void cargarTablaProductos() {
        ProductoBO productoBO = new ProductoBO();
        productoBO.listaProducto(tblProductos);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificarProducto;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCategoriaProducto;
    private javax.swing.JLabel lblDescripcionProducto;
    private javax.swing.JLabel lblIdProducto;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblPrecioProducto;
    private javax.swing.JLabel lblStockProducto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panProducto;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextArea txaDescripcionProducto;
    private javax.swing.JTextField txtCategoriaProducto;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecioProducto;
    private javax.swing.JTextField txtStockProducto;
    // End of variables declaration//GEN-END:variables
}
