/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.automercado.ui;

import com.automercado.bo.ProveedorBO;
import com.automercado.entity.Proveedor;
import javax.swing.JOptionPane;

/**
 *
 * @author kev17
 */
public class FrmProveedor extends javax.swing.JFrame {

    /**
     * Creates new form FrmProveedor
     */
    private ProveedorBO provbo = new ProveedorBO();

    public FrmProveedor() {
        initComponents();
        setLocationRelativeTo(null);
        cargarTablaProveedores();
    }

    public void listarProveedor() {
        provbo.listaProveedor(tblProveedores);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblIdProveedor = new javax.swing.JLabel();
        lblNombreProveedor = new javax.swing.JLabel();
        lblDireccionProveedor = new javax.swing.JLabel();
        lblTelefonoProveedor = new javax.swing.JLabel();
        lblCorreoElectronicoProveedor = new javax.swing.JLabel();
        lblProductoProveedor = new javax.swing.JLabel();
        txtProductoProveedor = new javax.swing.JTextField();
        txtCorreoElectronicoProveedor = new javax.swing.JTextField();
        txtIdProveedor = new javax.swing.JTextField();
        txtNombreProveedor = new javax.swing.JTextField();
        txtTelefonoProveedor = new javax.swing.JTextField();
        btnAgregarProveedor = new javax.swing.JButton();
        btnModificarProveedor = new javax.swing.JButton();
        btnEliminarProveedor = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProveedores = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDireccionProveedor = new javax.swing.JTextArea();
        lblImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblTitulo.setText("PROVEEDORES");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        lblIdProveedor.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblIdProveedor.setText("ID:");
        jPanel1.add(lblIdProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        lblNombreProveedor.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblNombreProveedor.setText("NOMBRE:");
        jPanel1.add(lblNombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 30));

        lblDireccionProveedor.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblDireccionProveedor.setText("DIRECCION:");
        jPanel1.add(lblDireccionProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        lblTelefonoProveedor.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblTelefonoProveedor.setText("TELEFONO:");
        jPanel1.add(lblTelefonoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 30));

        lblCorreoElectronicoProveedor.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblCorreoElectronicoProveedor.setText("CORREO ELECTRONICO:");
        jPanel1.add(lblCorreoElectronicoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, 30));

        lblProductoProveedor.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblProductoProveedor.setText("PRODUCTO:");
        jPanel1.add(lblProductoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 30));

        txtProductoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductoProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(txtProductoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 100, 30));

        txtCorreoElectronicoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoElectronicoProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(txtCorreoElectronicoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 230, 30));

        txtIdProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 100, 30));

        txtNombreProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 220, 30));

        txtTelefonoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelefonoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 220, 30));

        btnAgregarProveedor.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnAgregarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automercado/icon/mas_icon.png"))); // NOI18N
        btnAgregarProveedor.setText("Agregar");
        btnAgregarProveedor.setToolTipText("");
        btnAgregarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 120, 30));

        btnModificarProveedor.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnModificarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automercado/icon/editar_icon.png"))); // NOI18N
        btnModificarProveedor.setText("Modificar");
        btnModificarProveedor.setToolTipText("");
        btnModificarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 120, 30));

        btnEliminarProveedor.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnEliminarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automercado/icon/borrar_icon.png"))); // NOI18N
        btnEliminarProveedor.setText("Eliminar");
        btnEliminarProveedor.setToolTipText("");
        btnEliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 120, 30));

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automercado/icon/limpiar_icon.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setToolTipText("");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 120, 30));

        btnVolver.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automercado/icon/atras_icon.png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setToolTipText("");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 50, 110, 30));

        tblProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProveedoresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProveedores);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 87, 480, 390));

        txaDireccionProveedor.setColumns(10);
        txaDireccionProveedor.setLineWrap(true);
        txaDireccionProveedor.setRows(5);
        txaDireccionProveedor.setTabSize(1);
        txaDireccionProveedor.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txaDireccionProveedor);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 340, 80));

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/automercado/img/proveedores.jpg"))); // NOI18N
        jPanel1.add(lblImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoElectronicoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoElectronicoProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoElectronicoProveedorActionPerformed

    private void txtIdProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProveedorActionPerformed

    private void txtNombreProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProveedorActionPerformed

    private void txtTelefonoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoProveedorActionPerformed

    private void txtProductoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductoProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductoProveedorActionPerformed

    private void btnAgregarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProveedorActionPerformed
        if (txtNombreProveedor.getText().isEmpty() || txtTelefonoProveedor.getText().isEmpty()
                || txaDireccionProveedor.getText().isEmpty() || txtCorreoElectronicoProveedor.getText().isEmpty()
                || txtProductoProveedor.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Por favor complete todos los campos");
        } else {
            Proveedor proveedor = new Proveedor();
            proveedor.setNombre_Proveedor(txtNombreProveedor.getText());
            proveedor.setDireccion(txaDireccionProveedor.getText());
            proveedor.setTelefono(txtTelefonoProveedor.getText());
            proveedor.setCorreo_Electronico(txtCorreoElectronicoProveedor.getText());
            proveedor.setId_Producto(Integer.parseInt(txtProductoProveedor.getText()));

            ProveedorBO proveedorBO = new ProveedorBO();
            String mensaje = proveedorBO.agregarProveedor(proveedor);

            JOptionPane.showMessageDialog(null, mensaje);
            limpiar();
            cargarTablaProveedores();
        }
    }//GEN-LAST:event_btnAgregarProveedorActionPerformed

    private void btnModificarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProveedorActionPerformed
        if (txtIdProveedor.getText().isEmpty() || txtNombreProveedor.getText().isEmpty()
                || txtTelefonoProveedor.getText().isEmpty() || txaDireccionProveedor.getText().isEmpty()
                || txtCorreoElectronicoProveedor.getText().isEmpty() || txtProductoProveedor.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Por favor complete todos los campos");
        } else {
            Proveedor proveedor = new Proveedor();
            proveedor.setId_Proveedor(Integer.parseInt(txtIdProveedor.getText()));
            proveedor.setNombre_Proveedor(txtNombreProveedor.getText());
            proveedor.setDireccion(txaDireccionProveedor.getText());
            proveedor.setTelefono(txtTelefonoProveedor.getText());
            proveedor.setCorreo_Electronico(txtCorreoElectronicoProveedor.getText());
            proveedor.setId_Producto(Integer.parseInt(txtProductoProveedor.getText()));

            ProveedorBO proveedorBO = new ProveedorBO();
            String mensaje = proveedorBO.modificarProveedor(proveedor);

            JOptionPane.showMessageDialog(null, mensaje);
            limpiar();
            cargarTablaProveedores();
        }
    }//GEN-LAST:event_btnModificarProveedorActionPerformed

    private void btnEliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProveedorActionPerformed
        if (txtIdProveedor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el ID del proveedor a eliminar");
        } else {
            ProveedorBO proveedorBO = new ProveedorBO();
            String mensaje = proveedorBO.eliminarProveedor(Integer.parseInt(txtIdProveedor.getText()));

            JOptionPane.showMessageDialog(null, mensaje);
            limpiar();
            cargarTablaProveedores();
        }
    }//GEN-LAST:event_btnEliminarProveedorActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        FrmIndex frmind = new FrmIndex();
        frmind.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void tblProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProveedoresMouseClicked
        int seleccion = tblProveedores.rowAtPoint(evt.getPoint());
        txtIdProveedor.setText(tblProveedores.getValueAt(seleccion, 0) + "");
        txtNombreProveedor.setText(tblProveedores.getValueAt(seleccion, 1) + "");
        txaDireccionProveedor.setText(tblProveedores.getValueAt(seleccion, 2) + "");
        txtTelefonoProveedor.setText(tblProveedores.getValueAt(seleccion, 3) + "");
        txtCorreoElectronicoProveedor.setText(tblProveedores.getValueAt(seleccion, 4) + "");
        txtProductoProveedor.setText(tblProveedores.getValueAt(seleccion, 5) + "");
    }//GEN-LAST:event_tblProveedoresMouseClicked

    public void limpiar() {
        txtIdProveedor.setText("");
        txtNombreProveedor.setText("");
        txaDireccionProveedor.setText("");
        txtTelefonoProveedor.setText("");
        txtCorreoElectronicoProveedor.setText("");
        txtProductoProveedor.setText("");
    }

    private void cargarTablaProveedores() {
        ProveedorBO proveedorBO = new ProveedorBO();
        proveedorBO.listaProveedor(tblProveedores);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProveedor;
    private javax.swing.JButton btnEliminarProveedor;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificarProveedor;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCorreoElectronicoProveedor;
    private javax.swing.JLabel lblDireccionProveedor;
    private javax.swing.JLabel lblIdProveedor;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblNombreProveedor;
    private javax.swing.JLabel lblProductoProveedor;
    private javax.swing.JLabel lblTelefonoProveedor;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblProveedores;
    private javax.swing.JTextArea txaDireccionProveedor;
    private javax.swing.JTextField txtCorreoElectronicoProveedor;
    private javax.swing.JTextField txtIdProveedor;
    private javax.swing.JTextField txtNombreProveedor;
    private javax.swing.JTextField txtProductoProveedor;
    private javax.swing.JTextField txtTelefonoProveedor;
    // End of variables declaration//GEN-END:variables
}
